remote: true
remote-name: origin
tag-prefix: v
branches:
  - name: main
rules:
  minor:
    - feat
  patch:
    - fix
    - perf
    - revert
    - build
    - chore
    - ci
    - docs
    - refactor
    - style
    - test